# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 229f729ddb712d9bc873425fede1e529f610c69a1185b96622e4292ad0bf2720c4662db5ca78d45f3105ecc7e0c6085658ea8f33e4c3fd550251e4c74acf998c

test:
  secret_key_base: 24f5aa10095fd690825975e264dc29f62de08c2253e1859989c4e1be3a584814849949d48904e98d5a46ad763db942fd2c907f61a487588bf99d6f9dcf03fea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
